@startuml
class HomeController{
}

class UserController {
    + List()
    + GetUser()
    + Lock()
    + Update()
    + Delete()
}

class AccountController {
    +Login()
    +Register()
    +Logout()
    +ResetPassword()
}

class ProfileController {
    + Get()
    + UpdateProfile()
}

class MessageController {
    + SendMessage()
    + Delete()
    + Update()
}

class GroupController {
    + List()
    + GetGroup()
    + AddMember()
    + RemoveMember()
    + ChangeAdmin()
    + Create()
    + Update()
    + Delete()
}

class ContactController {
    + List()
    + GetContact()
    + Add()
    + Remove()
}

class NotificationController {
    + List()
    + Create()
    + Delete()
}
@enduml
