@startuml

package "ASPNET IDENTITY" #B4A7E5 {
    entity aspnet_roles  {
        *id: int <<PK>>
        --
        name: varchar(20)
        ...
    }

    entity aspnet_user_roles{
        *user_id: int <<PK>> <<FK>>
        *role_id: int <<PK>> <<FK>>
    }
}

entity users {
    *id: int <<PK>>
    --
    name: varchar(30)
    surname: varchar(30)
    patronymic: varchar(30)
    username: varchar(100) <<unique>>
    email: varchar(50) <<unique>>
    telephone: varchar(11) <<nullable>>
    password_hash: varchar(255)
    about: varchar(255)
    image: blob
    last_activity: datetime
    status_id: int <<FK>>
    updated_at: datetime
    created_at: datetime
    ...
}

entity status{
    *id: int <<PK>>
    --
    name: varchar(100)
}

entity messages {
    *id: int <<PK>>
    --
    content: varchar(500)
    file_path: varchar(500)
    file_name: varchar(200)
    sender_id: int <<FK>>
    group_id: int <<FK>>
    parent_message_id: int <<FK>>
    is_deleted: boolean
    updated_at: datetime
    created_at: datetime
}

entity groups {
    *id: int <<PK>>
    --
    name: varchar(255)
    description: varchar(200)
    admin_user_id: int <<FK>> <<nullable>>
    group_type_id: int <<FK>>
    is_group: boolean
    updated_at: datetime
    created_at: datetime
}

entity group_members {
    *id: int <<PK>>
    --
    group_id: int <<FK>>
    user_id: int <<FK>>
    created_at: datetime
}

entity contacts {
    *id: int <<PK>>
    --
    user_id: int <<FK>>
    contact_user_id: int <<FK>>
    type: int
    created_at: datetime
}

entity notifications {
    *id: int <<PK>>
    --
    user_id int <<FK>>,
    content varchar(250),
    created_at: datetime
}

aspnet_user_roles }|-- aspnet_roles
aspnet_user_roles }|-- users
notifications }|-- users
group_members }|-- users
contacts }|-- users
messages }|-- users
users }|-- status
group_members }|-- groups
messages }|-- groups
messages ||-- messages

@enduml
